extends:
  - '@meyfa/eslint-config'
  - 'plugin:jsdoc/recommended'

parserOptions:
  project: './tsconfig.eslint.json'

rules:
  'jsdoc/require-param-type': off
  'jsdoc/require-returns-type': off
  'jsdoc/no-types': error
